# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkOrSlipNum',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.CharField(default='CREDIT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
