# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankData', '0002_auto_20161104_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='postingDate',
        ),
    ]
