# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
